FROM continuumio/miniconda3
RUN conda update -y conda
RUN conda install -c conda-forge -y gdal
RUN conda install -c conda-forge -y scipy
RUN conda install -c conda-forge -y matplotlib-base
RUN conda install -c conda-forge -y statsmodels
RUN conda install -c conda-forge -y scikit-image

WORKDIR /project
RUN mkdir /project/outputs
RUN mkdir /project/inputs
LABEL maintainer="jsolly"
COPY inputs/test.py /project/inputs/test.py

CMD ["python3", "inputs/test.py"]