# Inspired by https://github.com/wesfloyd/bacalhau_socat_test/blob/main/Dockerfile

# Any working directory can be chosen as per choice like '/' or '/home' etc

FROM osgeo/gdal
RUN apt-get update -y
RUN apt-get install -y python3-pip
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install matplotlib
RUN python3 -m pip install scipy
RUN python3 -m pip install statsmodels
RUN python3 -m pip install scikit-image

LABEL maintainer="jsolly"
WORKDIR /project/inputs
RUN mkdir ../outputs

# CMD ["python3", "inputs/test.py"]
CMD ["python3", "fmask_4_3.py", "LC08_L1TP_152028_20160209_20200907_02_T1/LC08_L1TP_152028_20160209_20200907_02_T1_MTL.txt", "../outputs"]