# Inspired by https://github.com/wesfloyd/bacalhau_socat_test/blob/main/Dockerfile

# Any working directory can be chosen as per choice like '/' or '/home' etc

FROM continuumio/miniconda3:latest
RUN conda update -y conda
RUN conda install -c conda-forge -y gdal
RUN conda install -c conda-forge -y scipy
RUN conda install -c conda-forge -y matplotlib-base
RUN conda install -c conda-forge -y statsmodels
RUN conda install -c conda-forge -y scikit-image
# RUN conda install -c conda-forge -y scikit-learn
RUN conda install -c conda-forge -y gdal
LABEL maintainer="jsolly"
WORKDIR /project/inputs
RUN mkdir ../outputs

# CMD ["python3", "inputs/test.py"]
CMD ["python3", "fmask_4_3.py", "LC08_L1TP_152028_20160209_20200907_02_T1/LC08_L1TP_152028_20160209_20200907_02_T1_MTL.txt", "../outputs"]