# Inspired by https://github.com/wesfloyd/bacalhau_socat_test/blob/main/Dockerfile

# Any working directory can be chosen as per choice like '/' or '/home' etc

FROM continuumio/miniconda3
RUN conda install -c conda-forge gdal
RUN conda install -c conda-forge scipy
RUN conda install -c conda-forge scikit-image
RUN conda install -c conda-forge statsmodels
RUN conda install -c conda-forge matplotlib-base

WORKDIR /project
RUN mkdir /project/outputs
LABEL maintainer="jsolly"

COPY fmask_4_3.py /project
COPY test.py /project
CMD ["python3", "test.py"]