
FROM osgeo/gdal
RUN apt-get update -y
RUN apt-get install -y python3-pip
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install matplotlib
RUN python3 -m pip install scikit-image
RUN python3 -m pip install numpy

LABEL maintainer="jsolly"
RUN mkdir -p /project/outputs
WORKDIR /project/inputs

COPY ./inputs/segmentation_testbed_2.py /project/inputs
COPY test1.txt /project/inputs


CMD ["python3", "segmentation_testbed_2.py", "-f", "LC08_L1TP_001028_20220615_20220627_02_T1_mosaic.tif"]