FROM osgeo/gdal
RUN apt-get update -y
RUN apt-get install -y python3-pip
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install matplotlib
RUN python3 -m pip install scikit-image
RUN python3 -m pip install numpy

LABEL maintainer="jsolly"
WORKDIR /project/inputs
RUN mkdir ../outputs

# CMD ["python3", "inputs/test.py"]
CMD ["python3", "segmentation_testbed_2.py", "../outputs"]